spring:
  config:
    activate:
      on-profile: local

  datasource:
  #  url: jdbc:h2:tcp://localhost/C:\study\jpashop
  #  username: sa
  #  password:
  #  driver-class-name: org.h2.Driver

    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:13306/toongather?characterEncoding=UTF-8&serverTimezone=UTC
    username: webtoon
    password: toon123!@
    hikari:
      pool-name: SpringBootJPAHikariCP
      maximum-pool-size: 2
      idle-timeout: 10000
      connection-timeout: 10000
      validation-timeout: 10000
      max-lifetime: 28770000
      connection-init-sql: set wait_timeout = 600

  jpa:
    hibernate:
      ddl-auto: none
