spring:
  profiles:
    default: local
    active: local
    include:
      - oauth2

  jpa:
    properties:
      hibernate:
        format_sql: true
        physical_naming_strategy: com.toongather.toongather.global.config.UpperCaseNamingStrategy

logging.level:
  org.hibernate.SQL: debug