spring:
  profiles:
    default: local
    active: local
    include:
      - oauth2
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    properties:
      hibernate:
        format_sql: true
        physical_naming_strategy: com.toongather.toongather.global.config.UpperCaseNamingStrategy
        default_batch_fetch_size : 100

logging.level:
  org.hibernate.SQL: debug