#
#    H2 DB
#

spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/C:\study\jpashop    # 자신에 맞춰 바꾸기
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.H2Dialect


file:
  dir: /tmp