spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mariadb://localhost:13306/toongather?characterEncoding=UTF-8&serverTimezone=UTC # 운영에 맞게 바꿔야함
    username: webtoon
    password: toon123!@
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      pool-name: SpringBootJPAHikariCP
      maximum-pool-size: 2
      idle-timeout: 10000
      connection-timeout: 10000
      validation-timeout: 10000
      max-lifetime: 28770000
      connection-init-sql: set wait_timeout = 600

  jpa:
    hibernate:
      ddl-auto: none


