spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mariadb://localhost:13306/toongather?characterEncoding=UTF-8&serverTimezone=UTC # 운영에 맞게 바꿔야함
    username: webtoon
    password: toon123!@
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug