
  datasource:
    url: jdbc:mariadb://localhost:13306/toongather?characterEncoding=UTF-8&serverTimezone=UTC
    username: webtoon
    password: toon123!@
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none #update
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug